// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AboutMe() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"about-me\" class=\"glass-card p-4 md:p-8 my-16 mx-4 flex flex-col items-center md:w-[400px] lg:w-[550px] xl:w-[1000px]\"><h2 class=\"text-2xl font-bold mb-16 mt-4\">About me</h2><div><p>I’m a Software Engineer with 3+ years of professional experience building backend systems and full-stack applications. My work emphasizes performance, system reliability, and clean engineering, with core expertise in Go, Python, microservices, distributed systems, and real-time data flows.</p><p class=\"mt-4\">Over the years, I’ve contributed to projects across cybersecurity, cloud, analytics, and digital products—often owning both implementation and architectural design. I enjoy turning complex requirements into clean, maintainable services and working across the stack when it leads to a better product.</p><p class=\"mt-4\">Beyond day-to-day engineering, I’m driven by curiosity, continual learning, and creating software that feels purposeful. My goal is always to deliver solutions that are both technically solid and genuinely valuable to the people who use them.</p></div><div class=\"mt-12 mb-4 flex flex-col items-center\"><h2 class=\"text-xl mb-4\">Experience</h2><ul class=\"list-disc ml-4 lg:ml-8\"><li>Software Engineer @ IT Engine (Aug 2024 – Oct 2025)</li><li>Software Engineer @ Recall Taxi (Aug 2023 – July 2024)</li><li>Software Engineer @ Tangled Group Inc. (July 2022 – July 2023)</li></ul><h2 class=\"text-xl my-4 mt-8\">Education</h2><ul class=\"list-disc ml-4 lg:ml-8\"><li>Master of Applied Studies in Information Technology and Systems (Expected June 2027)</li><li>Bachelor of Applied Studies in Business Informatics (Oct 2023)</li><li>Computer Engineering Technician (June 2015)</li></ul></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
