// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"glass-card p-4 my-16 mx-4 flex flex-col items-center\"><div><img src=\"/static/logo.png\" fetchpriority=\"high\" alt=\"Logo of the website\" class=\"w-full rounded-2xl\"></div><div class=\"mt-8\"><div class=\"flex flex-col items-center\"><h1 class=\"text-2xl font-bold\">Milijan Mosić</h1><h2 class=\"text-xl\">Software Engineer</h2></div><div class=\"flex flex-col items-center my-16\"><p>Building reliable, scalable, and and modern applications — from microservices to full-stack solutions.</p><quote class=\"mt-4\">Positivity. Passion. Perseverance.</quote></div><div class=\"flex justify-center mb-4\"><a href=\"/#contact-me\" class=\"transition-all duration-75 ease-linear text-lg rounded-full p-2 px-4 bg-sky-800 border-1 border-sky-500 hover:border-white hover:bg-white hover:text-black hover:cursor-pointer mr-2\">Hire me</a> <a href=\"/#projects\" class=\"glass-card ml-2 p-2 px-4 hover:bg-white text-lg flex items-center justify-center\">My work</a></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
