// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"glass-card p-4 m-4\"><div><img src=\"/static/me.jpg\" class=\"w-full rounded-2xl\"></div><div class=\"mt-8\"><div class=\"flex flex-col items-center\"><h1 class=\"text-2xl font-bold\">Milijan Mosić</h1><h2 class=\"text-xl\">Software Engineer</h2></div><div class=\"flex flex-col items-center my-8\"><p>Building efficient, scalable, and secure systems — from microservices to full-stack solutions.</p><quote class=\"mt-4 text-gray-600\">Positivity. Passion. Perseverance.</quote></div><div class=\"flex justify-center\"><a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-solid fa-location-dot\"></i></a> <a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-solid fa-envelope\"></i></a> <a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-brands fa-github\"></i></a> <a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-brands fa-linkedin\"></i></a></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
