// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CTA() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"contact-me\" class=\"glass-card p-4 md:p-8 my-16 mx-4 flex flex-col items-center md:w-[400px] lg:w-[550px] xl:w-[1000px]\"><h2 class=\"text-2xl font-bold mb-16 mt-4\">Contact Me</h2><form id=\"contact-form\" class=\"flex flex-col gap-8 w-full\"><div class=\"flex flex-col items-center w-full\"><label for=\"name\" class=\"block mb-1\">Name</label> <input required type=\"text\" id=\"name\" name=\"name\" class=\"w-full lg:w-1/2 p-2 rounded-xl bg-white/25 border-2 border-white/0 focus:outline-none focus:border-white\"></div><div class=\"w-full flex flex-col items-center\"><label for=\"email\" class=\"block mb-1\">Email</label> <input required type=\"email\" id=\"email\" name=\"email\" class=\"w-full lg:w-1/2 p-2 rounded-xl bg-white/25 border-2 border-white/0 focus:outline-none focus:border-white\"></div><div class=\"w-full flex flex-col items-center\"><label for=\"request\" class=\"block mb-1\">Request</label> <textarea required id=\"request\" name=\"request\" rows=\"7\" class=\"w-full lg:w-1/2 p-2 rounded-xl bg-white/25 border-2 border-white/0 focus:outline-none focus:border-white\"></textarea></div><div class=\"flex flex-col items-center\"><!-- Status request --><p id=\"contact-status\" class=\"text-xl mt-4 rounded-full p-4 md:p-8\"></p><button id=\"submit-button\" type=\"submit\" class=\"transition-all duration-75 ease-linear text-lg rounded-full p-2 px-8 mb-4 bg-sky-800 border-1 border-sky-500 hover:border-white hover:bg-white hover:text-black hover:cursor-pointer\">Send request</button></div></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
