// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "time"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"glass-card p-4 my-16 mx-4 flex flex-col items-center\"><div class=\"flex flex-col mt-4\"><p>© ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().Year())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/index/footer.templ`, Line: 8, Col: 28}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " Milijan Mosić — Software Engineer</p><p class=\"mt-4\">Based in Serbia — Working worldwide</p></div><div class=\"flex flex-row justify-between my-16 text-sm w-full\"><div class=\"flex flex-col w-1/2 gap-4\"><a href=\"/#about-me\" class=\"underline\">About Me</a> <a href=\"/#services\" class=\"underline\">Services</a> <a href=\"/#skills\" class=\"underline\">Skills</a></div><div class=\"flex flex-col w-1/2 gap-4\"><a href=\"/#projects\" class=\"underline\">Projects</a> <a href=\"/#testimonials\" class=\"underline\">Testimonials</a> <a href=\"/#contact-me\" class=\"underline\">Contact Me</a></div></div><div class=\"flex mb-4\"><a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-solid fa-location-dot\"></i></a> <a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-solid fa-envelope\"></i></a> <a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-brands fa-github\"></i></a> <a href=\"#\" class=\"glass-card w-12 h-12 m-1 hover:bg-white text-2xl flex items-center justify-center\"><i class=\"fa-brands fa-linkedin\"></i></a></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
