// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

type Skill struct {
	Icon string
	Name string
}

type Group struct {
	Title  string
	Skills []Skill
}

var frontendSkills = []Skill{
	{Icon: "react", Name: "React"},
	{Icon: "language-typescript", Name: "TypeScript"},
	{Icon: "tailwind", Name: "Tailwind CSS"},
	{Icon: "lightning-bolt", Name: "Vite"},
}
var frontend = Group{Title: "Frontend", Skills: frontendSkills}

var backendSkills = []Skill{
	{Icon: "language-go", Name: "Go"},
	{Icon: "language-python", Name: "Python"},
	{Icon: "nodejs", Name: "NodeJS"},
	{Icon: "database-search", Name: "SQL"},
}
var backend = Group{Title: "Backend", Skills: backendSkills}

var databaseSkills = []Skill{
	{Icon: "database", Name: "PostgreSQL"},
	{Icon: "leaf", Name: "MongoDB"},
	{Icon: "bird", Name: "MinIO"},
	{Icon: "duck", Name: "DuckDB"},
}
var database = Group{Title: "Databases", Skills: databaseSkills}

var technologiesSkills = []Skill{
	{Icon: "aws", Name: "AWS"},
	{Icon: "git", Name: "Git"},
	{Icon: "menu", Name: "Redis"},
	{Icon: "apache-kafka", Name: "Kafka"},
	// {Icon: "rabbit", Name: "RabbitMQ"},
}
var technologies = Group{Title: "Technologies", Skills: technologiesSkills}

var sysAdminSkills = []Skill{
	{Icon: "penguin", Name: "Linux"},
	{Icon: "bash", Name: "Bash"},
	{Icon: "lock", Name: "Caddy"},
	{Icon: "server", Name: "Ngnix"},
}
var sysAdmin = Group{Title: "System Administration", Skills: sysAdminSkills}

var devOpsSkills = []Skill{
	{Icon: "gitlab", Name: "GitLab CI"},
	{Icon: "crosshairs", Name: "Argo CD"},
	{Icon: "docker", Name: "Docker"},
	{Icon: "kubernetes", Name: "Kubernetes"},
	// {Icon: "chart-bar", Name: "Grafana"},
	// {Icon: "torch", Name: "Prometheus"},
}
var devOps = Group{Title: "DevOps", Skills: devOpsSkills}

var allSkillGroups = []Group{
	frontend,
	backend,
	database,
	technologies,
	sysAdmin,
	devOps,
}

func Skills() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"skills\" class=\"glass-card p-4 md:p-8 my-16 mx-4 flex flex-col items-center md:w-[400px] lg:w-[550px] xl:w-[1000px]\"><h2 class=\"text-2xl font-bold mb-8 lg:mb-0 mt-4\">Skills</h2><div class=\"flex flex-row flex-wrap mb-4 lg:mb-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, group := range allSkillGroups {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex flex-col items-center w-full lg:w-1/2\"><h2 class=\"text-xl mt-16 mb-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(group.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/index/skills.templ`, Line: 82, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</h2><div class=\"flex flex-wrap\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, skill := range group.Skills {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex flex-col items-center w-1/2 lg:w-24 my-2 hover:text-black hover:bg-white transition-all duration-75 ease-linear rounded-xl\"><div class=\"flex flex-col items-center justify-center w-16 h-16 text-3xl\"><span id=\"icon\" class=\"iconify text-5xl\" data-icon=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("mdi-%s", skill.Icon))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/index/skills.templ`, Line: 88, Col: 95}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"></span></div><p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(skill.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/index/skills.templ`, Line: 90, Col: 23}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
