// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"glass-card p-4 md:p-8 mt-16 mx-4 flex flex-col lg:flex-row items-center lg:items-stretch md:w-[400px] lg:w-[550px] xl:w-[1000px]\"><div class=\"lg:w-1/3\"><img fetchpriority=\"high\" src=\"/static/images/logo.webp\" alt=\"Logo of the website\" class=\"w-full rounded-2xl\"></div><div class=\"mt-8 lg:mt-0 lg:ml-16 lg:w-2/3\"><div class=\"flex flex-col items-center lg:justify-start\"><h1 class=\"text-2xl font-bold\">Milijan Mosić</h1><h2 class=\"text-xl\">Software Engineer</h2></div><div class=\"flex flex-col items-center my-16 lg:my-12\"><p>Building reliable, scalable, and and modern applications — from microservices to full-stack solutions.</p><quote class=\"mt-4\">Positivity. Passion. Perseverance.</quote></div><div class=\"flex justify-center mb-4 lg:mb-0\"><a href=\"/#projects\" class=\"flex justify-center items-center p-2 px-6 mr-2 text-lg text-2xl rounded-full md:px-8 border-1 border-white/35 hover:text-black hover:bg-white animate\">My work</a> <a href=\"/#contact-me\" class=\"p-2 px-6 ml-2 text-lg bg-sky-800 rounded-full border-sky-500 animate md:px-8 border-1 hover:border-white hover:bg-white hover:text-black hover:cursor-pointer\">Hire me</a></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
