// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContactMe() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"contact-me\" class=\"glass-card p-4 md:p-8 my-16 mx-4 flex flex-col items-center md:w-[400px] lg:w-[550px] xl:w-[1000px]\"><h2 class=\"mt-4 mb-16 text-2xl font-bold\">Contact Me</h2><p class=\"mb-16\">Have an idea, a project, or a challenge you’d like to discuss? I’m always happy to connect and explore how we can work together.</p><form id=\"contact-form\" class=\"flex flex-col gap-8 w-full\"><div class=\"flex flex-col items-center w-full\"><label for=\"name\" class=\"mb-1 w-full lg:w-1/2\">Name</label> <input required id=\"name\" type=\"text\" name=\"name\" placeholder=\"William\" class=\"form-input\"></div><div class=\"flex flex-col items-center w-full\"><label for=\"email\" class=\"mb-1 w-full lg:w-1/2\">Email</label> <input required id=\"email\" type=\"email\" name=\"email\" placeholder=\"user@example.com\" class=\"form-input\"></div><div class=\"flex flex-col items-center w-full\"><label for=\"request\" class=\"mb-1 w-full lg:w-1/2\">Request</label> <textarea required id=\"request\" name=\"request\" rows=\"7\" placeholder=\"I have an idea for the project...\" class=\"form-input\"></textarea></div><div class=\"flex flex-col items-center w-full\"><!-- Status request --><p id=\"contact-status\" class=\"p-4 mt-4 text-xl rounded-full md:p-8\"></p><button id=\"submit-button\" type=\"submit\" class=\"p-2 px-6 mb-4 text-lg bg-sky-800 rounded-full border-sky-500 animate md:px-8 border-1 hover:border-white hover:bg-white hover:text-black hover:cursor-pointer\">Send request</button></div></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
