// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav id=\"navbar\" class=\"glass-card opacity-0 fixed z-50 w-full lg:hidden transition-opacity duration-75 rounded-b-xl rounded-t-none\"><div class=\"max-w-6xl mx-auto flex justify-between items-center p-2\"><img src=\"/static/logo.webp\" alt=\"Logo\" class=\"w-16 h-16 rounded-2xl\"> <button id=\"menuToggle\" class=\"lg:hidden p-4\" aria-label=\"Toggle menu\"><span id=\"menuIcon\" class=\"text-3xl\">☰</span></button></div><div id=\"mobileMenu\" class=\"lg:hidden overflow-hidden max-h-0 transition-all duration-75\"><div class=\"flex flex-col items-center\"><a class=\"w-full p-4 text-lg hover:bg-white hover:text-black transition-all duration-75 ease-linear font-medium\" href=\"/#about-me\">About Me</a> <a class=\"w-full p-4 text-lg hover:bg-white hover:text-black transition-all duration-75 ease-linear font-medium\" href=\"/#services\">Services</a> <a class=\"w-full p-4 text-lg hover:bg-white hover:text-black transition-all duration-75 ease-linear font-medium\" href=\"/#skills\">Skills</a> <a class=\"w-full p-4 text-lg hover:bg-white hover:text-black transition-all duration-75 ease-linear font-medium\" href=\"/#projects\">Projects</a> <a class=\"w-full p-4 text-lg hover:bg-white hover:text-black transition-all duration-75 ease-linear font-medium\" href=\"/#testimonials\">Testimonials</a> <a class=\"w-full p-4 text-lg hover:bg-white hover:text-black transition-all duration-75 ease-linear font-medium\" href=\"/#contact-me\">Contact Me</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
