// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "time"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"glass-card p-4 md:p-8 my-16 mx-4 flex flex-col lg:flex-row items-center md:w-[400px] lg:w-[550px] xl:w-[1000px]\"><div class=\"flex flex-col w-full\"><div class=\"flex flex-col items-center p-4 w-full text-sm lg:p-0 lg:items-start\"><p>Milijan Mosić — Software Engineer</p><p>Based in Serbia — Working worldwide</p><p>2025. — ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().Year())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/footer.templ`, Line: 11, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ".</p></div><div class=\"flex flex-row justify-center w-full lg:-ml-1 lg:justify-start lg:mt-4\"><a href=\"https://maps.app.goo.gl/Efgqkq4Y5NqMyK9Z8\" aria-label=\"Link to Novi Sad, Serbia on Google Maps\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-nav-link animate\"><img src=\"/static/icons/location-pin.svg\" class=\"w-7 h-7\"></a> <a href=\"mailto:milijan.mosic@gmail.com\" aria-label=\"Link for opening your app for sending email to Milijan\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-nav-link animate\"><img src=\"/static/icons/envelope.svg\" class=\"w-7 h-7\"></a> <a href=\"https://github.com/milijan-mosic\" aria-label=\"Link towards Milijan’s GitHub profile\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-nav-link animate\"><img src=\"/static/icons/github.svg\" class=\"w-6 h-6\"></a> <a href=\"https://linkedin.com/in/milijan-mosic\" aria-label=\"Link towards Milijan’s LinkedIn profile\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-nav-link animate\"><img src=\"/static/icons/linkedin.svg\" class=\"w-7 h-7\"></a></div></div><div class=\"flex flex-row justify-between mt-12 mb-4 w-full text-sm lg:my-0 lg:w-1/3\"><div class=\"flex flex-col gap-4 items-end pr-4 w-1/2 md:p-8 lg:p-0 lg:pr-4\"><a href=\"/#about-me\" class=\"underline\">About Me</a> <a href=\"/#services\" class=\"underline\">Services</a> <a href=\"/#skills\" class=\"underline\">Skills</a></div><div class=\"flex flex-col gap-4 items-start pl-4 w-1/2 md:p-8 lg:p-0 lg:pl-4\"><a href=\"/#projects\" class=\"underline\">Projects</a> <a href=\"/#testimonials\" class=\"underline\">Testimonials</a> <a href=\"/#contact-me\" class=\"underline\">Contact Me</a></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
