// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav id=\"navbar\" class=\"fixed z-50 w-full rounded-t-none rounded-b-3xl opacity-0 glass-card lg:hidden animate\"><div class=\"flex justify-between items-center p-2 mx-auto max-w-6xl\"><img src=\"/static/images/logo.webp\" alt=\"Logo of the website\" class=\"w-16 h-16 rounded-2xl\"> <button id=\"menuToggle\" class=\"p-1 lg:hidden\" aria-label=\"Toggle menu\"><img id=\"menuIcon\" src=\"/static/icons/bars.svg\" alt=\"Mobile menu icon\" class=\"w-8 h-8 text-2xl invert\"></button></div><div id=\"mobileMenu\" class=\"overflow-hidden max-h-0 lg:hidden animate\"><div class=\"flex flex-col items-center\"><a class=\"mobile-nav-link animate\" href=\"/#about-me\">About Me</a> <a class=\"mobile-nav-link animate\" href=\"/#services\">Services</a> <a class=\"mobile-nav-link animate\" href=\"/#skills\">Skills</a> <a class=\"mobile-nav-link animate\" href=\"/#projects\">Projects</a> <a class=\"mobile-nav-link animate\" href=\"/#testimonials\">Testimonials</a> <a class=\"mobile-nav-link animate\" href=\"/#contact-me\">Contact Me</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
